### ISSUE TITLE
Star and unstar button sometimes not working

### ISSUE THREAD

**Issue by maxloh** [git-touch/git-touch#47] opened 2020-04-04 15:12 UTC
Pressing star and unstar button in repo page sometimes does nothing

Demo video:
https://imgur.com/a/ZHyHcs2

In the video, I press star button multiple times.
The button was expected to be replaced by unstar button, but nothing happens.

**Comment by pd4d10** [comment] 2020-04-05 14:18
Hi, @maxloh , thanks for the feedback!

It seems caused by GitHub's token scope policy update. The solution would depend on the login approach:

1. Login with OAuth: Go to **Me** -> **Switch accounts** to login again. It would ask you the extra `notification` permission and please say yes.
2. Login with token: Go to https://github.com/settings/tokens and find the token used in GitTouch, add `notification` scope and save.

**Comment by maxloh** [comment] 2020-04-05 18:19
> Hi, @maxloh , thanks for the feedback!
> 
> It seems caused by GitHub's token scope policy update. The solution would depend on the login approach:
> 
> 1. Login with OAuth: Go to **Me** -> **Switch accounts** to login again. It would ask you the extra `notification` permission and please say yes.
> 2. Login with token: Go to https://github.com/settings/tokens and find the token used in GitTouch, add `notification` scope and save.

I tried the mentioned steps but the problem persists.

Clearing app data and login again cannot solve the problem too.

**Comment by pd4d10** [comment] 2020-04-06 03:06
Oh, there seems another problem with organization repo.

I'll try to fix this in the next release.

**Comment by pd4d10** [comment] 2020-10-05 13:34
Should have fixed in the latest v1.5.1. Sorry for the long wait!

**Closed by pd4d10** 2020-10-05 13:34 UTC
Labels: bug
